language: node_js
node_js: node

cache:
  directories:
    - node_modules

after_success: yarn report-coverage

deploy:
  provider: script
  script: yarn deploy-storybook --ci
  on:
    branch: master

notifications:
  email:
    on_success: never
    on_failure: never
