language: node_js

cache:
  yarn: true
  directories:
    - node_modules

after_success: yarn report-coverage

notifications:
  email:
    on_success: never
    on_failure: never

before_deploy:
  - yarn run prepare

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    tags: true
