language: node_js
node_js: node

cache:
  directories:
    - node_modules

after_success: yarn report-coverage
before_deploy: yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  local-dir: storybook-static
  on:
    branch: master

notifications:
  email:
    on_success: never
    on_failure: never
